### ISSUE TITLE
Great work!!!

### ISSUE THREAD

**Issue by j574144** [cristijora/vue-light-bootstrap-dashboard#12]
Hi Cristi. 

This is Joaquin entering in touch with you about vue-light-bootstrap-dashboard. Firstly I want to congrat for great work about it.

Recently I have integrate the vue-light-bootstrap-dashboard with Laravel and is great by your architecture and develop concept on vue-light-bootstrap-dashboard, this made more easy this integrate. 

I have migrate mi personal Blog to your vue-light-bootstrap-dashboard and I wanted to share this to you.

Please visit: https://www.blog.joaquinlozanoc.ml/home 

Note: This is only content part, still is pending to migrate user session and comments part

Regards

**Comment by cristijora** [comment]
Hi @j574144 Glad it was useful and made your development easier.

**Comment by j574144** [comment]
Sure, thanks.
