### ISSUE TITLE
Question: Vue Paper Dashboard Pro Bootstrap 4

### ISSUE THREAD

**Issue by Extarys** [cristijora/vue-light-bootstrap-dashboard#15]
Hi there!

Will you make a paper dashboard using vue with bootstrap 4? :D

Sorry I didn't know where to ask this question.
Have a good day.

**Comment by cristijora** [comment]
Hi @Extarys 
Yes, it will be converted to BS4 but I'm waiting for an original HTML version from creative-tim to be converted first so I don't spend too much time on it.

**Comment by Extarys** [comment]
Awesome thanks!
I'll keep an eye out!
