### ISSUE TITLE
I found two typos

### ISSUE THREAD

**Issue by Nbsaw** [cristijora/vue-light-bootstrap-dashboard#8]
Hi @cristijora . Thanks for this great design!

![image](https://user-images.githubusercontent.com/12481935/34336162-e55e01ee-e98f-11e7-980b-7655cc20dafe.png)

But I found two typos in `user profile` view . 

The first one should be `light-bootstrap` and the second one should be `email`. 

If you think there is a problem, I can help you modify it.   ❤️

**Comment by cristijora** [comment]
Thanks a lot for reporting @Nbsaw if you have the time and pleasure, feel free to submit a PR. Happy holidays :)
